name: 'Steplix notify'
description: 'Notify slack using templates'
inputs:
  template:
    required: true
    default: "push"
  slack_webhook_url:
    required: true
    
runs:
  using: "composite"
  steps:
    - run: echo Notifying Slack
      shell: bash
    - name: Change directory to action path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: slack - GitHub Actions Slack integration
      uses: act10ns/slack@v2.0.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        config: ${{ inputs.template }}.yml
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}