name: 'Steplix notify'
description: 'Notify slack using templates'
inputs:
  template:
    required: true
    default: "push"
  slack_webhook_url:
    required: false
  status:
    required: false
    
runs:
  using: "composite"
  steps:
    - run: echo Notifying Slack
      shell: bash
    - name: slack - GitHub Actions Slack integration
      uses: act10ns/slack@v2.0.0
      with:
        status: ${{ inputs.status || job.status }}
        steps: ${{ toJson(steps) }}
        config: ${{ github.action_path }}/templates/${{ inputs.template }}.yml
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url || env.SLACK_WEBHOOK_URL }}